---
# cPanel Git Deployment - copies pavotu-local/* to web root so site loads at disruptiveexperience.com/pavotu/
deployment:
  tasks:
    - export DEPLOYPATH=/home1/moose/disruptiveexperience.com/public_html/pavotu
    - mkdir -p "$DEPLOYPATH"
    - /bin/cp -rf pavotu-local/* "$DEPLOYPATH/"
    - chmod -R 755 "$DEPLOYPATH"
    - find "$DEPLOYPATH" -type f -exec chmod 644 {} \;
