---
# cPanel Git Deployment - copies pavotu-local contents to web root (disruptiveexperience.com/pavotu)
# Single task so DEPLOYPATH is set for all commands. deploy-last-run.txt confirms deploy ran.
deployment:
  tasks:
    - export DEPLOYPATH=/home1/moose/disruptiveexperience.com/public_html/pavotu && date > $DEPLOYPATH/deploy-last-run.txt && /bin/cp -rf $DEPLOYPATH/pavotu-local/. $DEPLOYPATH/ && chmod -R 755 $DEPLOYPATH && find $DEPLOYPATH -type f -exec chmod 644 {} \;
