---
# cPanel Git Deployment - runs from repo root; copy pavotu-local into repo root so site serves at /pavotu/
deployment:
  tasks:
    - /bin/cp -rf pavotu-local/. .
    - chmod -R 755 .
    - find . -path ./.git -prune -o -type f -exec chmod 644 {} \;
